#!/usr/bin/env bash
# Script to install an Nginx server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
service nginx restart
