#!/usr/bin/env bash
# Configure Nginx server so /redirect_me is redirects to another page

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.bayona.me/ permanent;' /etc/nginx/sites-available/default
