#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt update

sudo apt install -y haproxy=2.0\*
hgproxy_conf_file="/etc/haproxy/haproxy.cfg"

fname="frontend http"
fbind="bind *:80"
fmode="mode http"
fdefault="default_backend web-backend"
frontend="$fname\n\t$fbind\n\t$fmode\n\t$fdefault\n"

bname="backend web-backend"
bbalance="balance roundrobin"
bserver1="server 285992-web-01 54.162.83.79.80 check"
bserver2="server 285992-web-02 100.26.222.213.80 check"
backend="$bname\n\t$bbalance\n\t$bserver1\n\t$bserver2"

sudo sed -i "$ a $frontend" $hgproxy_conf_file
sudo sed -i "$ a $backend" $hgproxy_conf_file

sudo service haproxy start
