#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

apt-get update
apt-get -y install haproxy
printf "\n frontend holberton
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 285992-web-01 54.208.117.130
    server 285992-web-02 100.26.222.213" >> /etc/haproxy/haproxy.cfg
service haproxy start
