#!/usr/bin/env bash
# Displays to infinity and beyond indefinitely with 2 second sleep
#+ with "I am invincible inbetween each iteration"

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM
done
